services:
    proxy:
        container_name: ${PROJECT_NAME}_proxy
        image: nginxinc/nginx-unprivileged:stable-alpine
        depends_on:
            - app
        environment:
            STACK_NAME: ${PROJECT_NAME}
            WP_DEBUG: 0
        volumes:
            - ./public:/srv/app/public:ro
            - ./docker/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
            - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd
        networks:
            - https
            - app
        ports:
            - "800:8080"

    app:
        container_name: ${PROJECT_NAME}_app
        user: symfony
        build:
            context: .
            target: app_php_dev
        #        restart: unless-stopped
        depends_on:
            database:
                condition: service_healthy
                required: false
        volumes:
            - ./:/srv/app/
#            - /srv/app/var

        environment:
            PROJECT_NAME: ${PROJECT_NAME}
            MAILER_DSN: smtp://mailhog:1025
            DATABASE_URL: postgresql://${DATABASE_USERNAME:-app}:${DATABASE_PASSWORD:-secret}@database/${DATABASE_NAME:-app}?serverVersion=17&charset=utf8
            XDEBUG_MODE: 'debug'
            XDEBUG_CONFIG: 'mode=debug client_host=host.docker.internal idekey=phpstorm-xdebug start_with_request=trigger remote_handler=dbgp client_port=9003'
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - app


    database:
        profiles: ["db"]
        image: postgres:17
        container_name: ${PROJECT_NAME}_database
        environment:
            - POSTGRES_USER=${DATABASE_USERNAME:-app}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-secret}
            - POSTGRES_DB=${DATABASE_NAME:-app}
        volumes:
            - pg_data:/bitnami/postgresql

        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${DATABASE_NAME:-app}", "-U", "${DATABASE_USERNAME:-app}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        ports:
            - "5432:5432"

        networks:
            - app
            - adminer
        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!


    node:
        container_name: ${PROJECT_NAME}_node
        tty: true
        image: node:lts
        working_dir: /usr/src/app/
        volumes:
            - ./:/usr/src/app
            - ./docker/node/.npmrc:/root/.npmrc

        command: sh

    #    mailhog:
    #      image: mailhog/mailhog:latest
    #      container_name: ${PROJECT_NAME}_mailhog
    #      environment:
    #        - MH_STORAGE=maildir
    #      # volumes:
    #      #   - ./docker/mailhog/maildir:/maildir:rw,delegated
    #      networks:
    #        - app
    #      ports:
    #        - "1025:1025"
    #        - "8025:8025"


networks:
    https:
        external: true
    adminer:
        external: true
    app:
        name: ${PROJECT_NAME}_app

volumes:
    ###> doctrine/doctrine-bundle ###
    pg_data:
        name: ${PROJECT_NAME}_database
    ###< doctrine/doctrine-bundle ###
